### ISSUE TITLE
Cannot find sysfs_software_spi.so

### ISSUE THREAD

**Issue by harry88pl** [EdNekebno/DGTCentaurMods#183]
Traceback (most recent call last):
  File "/opt/DGTCentaurMods/game/menu.py", line 40, in <module>
    from DGTCentaurMods.board import *
  File "/usr/lib/python3/dist-packages/DGTCentaurMods/board/board.py", line 27, in <module>
    from DGTCentaurMods.display import epd2in9d, epaper
  File "/usr/lib/python3/dist-packages/DGTCentaurMods/display/epd2in9d.py", line 34, in <module>
    from DGTCentaurMods.display import epdconfig
  File "/usr/lib/python3/dist-packages/DGTCentaurMods/display/epdconfig.py", line 153, in <module>
    implementation = JetsonNano()
  File "/usr/lib/python3/dist-packages/DGTCentaurMods/display/epdconfig.py", line 112, in __init__
    raise RuntimeError('Cannot find sysfs_software_spi.so')
RuntimeError: Cannot find sysfs_software_spi.so

**Comment by EdNekebno** [comment]
You get this when the pi cannot communicate with the epaper. Which version of the centaur board do you have? 1 or 2. Also which version of DGTCentaurMods are you trying to run?

**Comment by harry88pl** [comment]
v1

**Comment by harry88pl** [comment]
It worked with this version:

Raspberry Pi OS Lite (Legacy)
Release date: May 3rd, 2023
System: 32-bit
Kernel version: 5.10
Debian version: 10 (buster)

I just couldn't get Bluetooth to work, so I updated to Debian 11.

**Comment by harry88pl** [comment]
The file indeed doesn't exist:

```plaintext
harry88pl@harry:/usr/lib/python3/dist-packages/DGTCentaurMods/display $ dir -l
total 96
-rw-r--r-- 1 pi   pi    1749 Oct  5 16:10 cchandler.py
-rw-r--r-- 1 pi   pi    4868 Oct  5 16:10 chromecast.py
-rw-r--r-- 1 pi   pi    3864 Oct  5 16:10 epaper_driver.py
-rwxr-xr-x 1 pi   pi   22620 Oct  5 16:10 epaperDriver.so
-rw-r--r-- 1 pi   pi   22607 Oct  5 16:10 epaper.py
-rw-r--r-- 1 pi   pi   12538 Oct  5 16:10 epd2in9d.py
-rw-r--r-- 1 pi   pi    4987 Oct  5 16:10 epdconfig.py
-rw-r--r-- 1 pi   pi      61 Oct  5 16:10 __init__.py
drwxr-xr-x 2 root root  4096 Oct  7 22:32 __pycache__
```

**Comment by harry88pl** [comment]
However, I'm not 100% certain if I have version 1, as the only information I can find on the PCB is that it's from December 2019, and there's no further detail.

**Comment by EdNekebno** [comment]
Okay, that makes sense already. Debian doesn't have the right drivers in it. We haven't yet found a way for it not to be Raspbian 32 bit. What was wrong with the bluetooth?

**Comment by harry88pl** [comment]
Everything was working, you could play on Lichess and run DGT Centaur. However, the `bluetoothctl` command didn't display anything; it just got stuck, and the only thing that worked was pressing CTRL+C to cancel it.

**Comment by EdNekebno** [comment]
With raspbian 32 bit? Did you have wifi?

**Comment by harry88pl** [comment]
Yes, it worked on this Debian version:

Raspberry Pi OS Lite (Legacy)
Release date: May 3rd, 2023
System: 32-bit
Kernel version: 5.10
Debian version: 10 (Buster)

And the Wi-Fi was also functioning. I installed everything through SSH, including DGTMods.

**Comment by EdNekebno** [comment]
Did you apt upgrade and apt update?

**Comment by harry88pl** [comment]
I performed the updates as outlined in this guide:

https://www.tomshardware.com/how-to/upgrade-raspberry-pi-os-to-bullseye-from-buster

Now, I will be reinstalling Debian 10, at least to have Bluetooth working again. Previously, before deciding to go for Debian 11, I tried everything to get Bluetooth running on Debian 10, but unfortunately, nothing seemed to help. However, I'll give it another try.

**Comment by EdNekebno** [comment]
Perhaps could try:
sudo systemctl disable hciuart.service
sudo systemctl enable bluetooth.service

possibly check it isn't disabled in /boot/config.txt .

For the error - the waveshare file used falls back to assuming you have a raspberry pi in specific circumstances. Then the message can be somewhat deceptive because it's looking for that for a jetson nano. let me check...

**Comment by EdNekebno** [comment]
It uses the existence of /sys/bus/platform/drivers/gpiomem-bcm2835 to determine if it's a raspberry pi or not. You won't get the same error message on 1.3.2 though as it's a different driver. But it indicates where the problem is I guess.

**Comment by EdNekebno** [comment]
That driver is apparently only in Raspbian OS.
